name: building, linting, testing
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [19.x]

    steps:
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        if: runner.os == 'Linux'

      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build production
        run: npm run build:prod
        if: always()

      - name: Lint ts
        run: npm run lint:ts
        if: always()

      - name: Lint scss
        run: npm run lint:scss

      - name: Unit testing
        run: npm run test:unit
        if: always()

      - name: Build Storybook
        run: npm run storybook:build
        if: always()

      - name: Screenshot testing
        run: npm run test:ui:ci
        if: always()
